[build]
target = "x86_64-unknown-none.json"

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-Tkernel/linker.ld"]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
